name = "logosophe-email"
main = "app/index.ts"
compatibility_date = "2024-12-30"

[env.local-dev]
name = "logosophe-email-local-dev"

[env.local-dev.d1_databases]
binding = "DB"
database_name = "contact_submissions"
database_id = "existing-contact-submissions-id" 