name = "logosophe-email"
main = "app/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

# Use the same account as the frontend
account_id = "911edf2379732c1038a6a894cae9bee5"

[observability.logs]
enabled = true

[vars]
# These will be set in the Cloudflare dashboard
EMAIL_FROM_ADDRESS = "info@logosophe.com"
EMAIL_TO_ADDRESS = "info@logosophe.com"

[[d1_databases]]
binding = "DB"
database_name = "contact_submissions"
database_id = "b8c70fef-f207-4216-9215-cb3b886938b5"

[[send_email]]
name = "EMAIL"
destination_address = "info@logosophe.com" 