name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    name: Test and Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Enable Corepack
        run: corepack enable
      
      - name: Setup Yarn
        run: |
          yarn set version stable --yarn-path
          yarn install --immutable
      
      - name: Type Check
        run: yarn workspace worker tsc --noEmit
      
      - name: Build Worker
        run: yarn workspace worker build
      
      - name: Build Email Worker
        run: yarn workspace email-worker build
