on: [push]
jobs:
  deploy-email-worker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy Email Worker to Cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Enable Corepack
        run: corepack enable
      - name: Yarn Set Version
        run: yarn set version latest --yarn-path
      - name: Yarn Install
        run: yarn install
      - name: Deploy Email Worker
        run: yarn workspace email-worker deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NODE_ENV: production 