on: [push]
jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy Worker to Cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Enable Corepack
        run: corepack enable
      
      - name: Setup Yarn
        run: |
          yarn set version stable --yarn-path
          yarn install --immutable
      
      - name: Deploy Worker
        run: |
          echo "Setting up environment variables..."
          export CLOUDFLARE_API_TOKEN="${{ secrets.CLOUDFLARE_API_TOKEN }}"
          export CLOUDFLARE_ACCOUNT_ID="${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          export NODE_ENV=production
          
          # Skew protection environment variables
          export CF_WORKER_NAME="logosophe"
          export CF_PREVIEW_DOMAIN="anchorwrite.workers.dev"
          export CF_WORKERS_SCRIPTS_API_TOKEN="${{ secrets.CF_WORKERS_SCRIPTS_API_TOKEN }}"
          export CF_ACCOUNT_ID="${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          
          # Production NextAuth environment variables
          export NEXTAUTH_URL="https://www.logosophe.com"
          export AUTH_URL="https://www.logosophe.com"
          export AUTH_REDIRECT_PROXY_URL="https://www.logosophe.com"
          
          echo "Deploying worker with skew protection..."
          cd apps/worker
          
          # Use OpenNext commands directly as recommended
          npx opennextjs-cloudflare build
          npx opennextjs-cloudflare deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NODE_ENV: production
          CF_WORKER_NAME: logosophe
          CF_PREVIEW_DOMAIN: anchorwrite.workers.dev
          CF_WORKERS_SCRIPTS_API_TOKEN: ${{ secrets.CF_WORKERS_SCRIPTS_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NEXTAUTH_URL: https://www.logosophe.com
          AUTH_URL: https://www.logosophe.com
          AUTH_REDIRECT_PROXY_URL: https://www.logosophe.com 